import { DataTypes } from 'sequelize';
import type { Migration } from '../migrate.js';

// "My data": what a chat visitor chose to save (profiles, tailored CVs, cover letters), keyed by their
// email, and its text in chunks with embeddings, for the chat's recall (RAG). Needs pgvector (the
// pgvector/pgvector:pg17 image in docker-compose.yml).
export const up: Migration = async ({ context: queryInterface }) => {
  await queryInterface.sequelize.query('CREATE EXTENSION IF NOT EXISTS vector');

  await queryInterface.createTable('my_data_documents', {
    // UUID v7, generated by the app (MyDataDocument model).
    id: { type: DataTypes.UUID, primaryKey: true, allowNull: false },
    // Lowercase. Not unique: one email has many documents, and every profile version is kept.
    email: { type: DataTypes.STRING, allowNull: false },
    // profile | tailored_cv | cover_letter. Not an enum: a new kind is a code change, not a migration.
    kind: { type: DataTypes.STRING(20), allowNull: false },
    title: { type: DataTypes.STRING(200), allowNull: false },
    // The block's JSON as the chat showed it.
    content: { type: DataTypes.JSONB, allowNull: false },
    createdAt: { type: DataTypes.DATE, allowNull: false },
  });
  // An email's documents of one kind, newest first: the current profile, and the list.
  await queryInterface.addIndex('my_data_documents', ['email', 'kind', 'createdAt'], { name: 'my_data_documents_email_kind_created_at' });

  await queryInterface.createTable('my_data_chunks', {
    id: { type: DataTypes.UUID, primaryKey: true, allowNull: false },
    documentId: {
      type: DataTypes.UUID,
      allowNull: false,
      references: { model: 'my_data_documents', key: 'id' },
      onDelete: 'CASCADE',
    },
    // Copied from the document, so a search filters by email without a join.
    email: { type: DataTypes.STRING, allowNull: false },
    text: { type: DataTypes.TEXT, allowNull: false },
    createdAt: { type: DataTypes.DATE, allowNull: false },
  });
  // all-MiniLM-L6-v2 vectors (384 dimensions), normalised, compared by cosine distance.
  await queryInterface.sequelize.query('ALTER TABLE my_data_chunks ADD COLUMN embedding vector(384) NOT NULL');
  await queryInterface.addIndex('my_data_chunks', ['email'], { name: 'my_data_chunks_email' });
  await queryInterface.addIndex('my_data_chunks', ['documentId'], { name: 'my_data_chunks_document_id' });
  await queryInterface.sequelize.query('CREATE INDEX my_data_chunks_embedding ON my_data_chunks USING hnsw (embedding vector_cosine_ops)');
};

export const down: Migration = async ({ context: queryInterface }) => {
  await queryInterface.dropTable('my_data_chunks');
  await queryInterface.dropTable('my_data_documents');
  // The extension stays: other database objects may use it, and it costs nothing unused.
};
